base_dir: /home/tomke/BNF_GESICA/copernicus_data_downloader

months: [
  "01", 
  # "02", "03", "04",
  # "05", "06", "07", "08", 
  # "09", "10", "11", "12"
]

years: [
  "2018",
  #  "2014", "2015", "2016", "2017", 
  # "2018", "2019", "2020", "2021", "2022", 
  # "2023", "2024", 
  # only available for interim analysis: "2025"
]
variables: [
  # "ozone",
  # "nitrogen_dioxide",
  # "particulate_matter_2.5um",
  # "particulate_matter_10um",
  "sulphur_dioxide"
]

level: ['0']


model: [
  "ensemble",
  # "match",
  # "emep",
  # "gemaq",
  # "mocage",
  # "silam",
  # "euradim",
  # "dehm",
  # "chimere",
  # "lotos",
  # "minni",
  # "monarch",
]


type: [
  "validated_reanalysis",
  # "interim_reanalysis"
]

postfix: "testttt"


### DO NOT TOUCH:

model_dict: 
  "ensemble": ENSa
  "match": SMHa
  "emep": EMPa
  "gemaq": GEMAQa
  "mocage": MFMa
  "silam": FMIa
  "euradim": RIUa
  "dehm": DEHMa
  "chimere": CHIa
  "lotos": KNMa
  "minni": MINNIa
  "monarch": MONARCHa


type_dict: 
  "validated_reanalysis": vra
  "interim_reanalysis": ira


variables_dict: 
  "ozone": "o3"
  "nitrogen_dioxide": "no2"
  "particulate_matter_2.5um": "pm2p5"
  "particulate_matter_10um": "pm10"
  "sulphur_dioxide": "so2"
